name: Build and publish Docusaurus Docs

on:
  pull_request:
    branches:
      - main
    # types:
    #   - closed

jobs:
  check-yarn-install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.20.2, 18.18.2]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn global add teraslice-cli
      - run: yarn list
