name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
    NODE_VERSIONS: ${{ vars.NODE_VERSIONS }}

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - run: |
        echo "NODE VERSIONS: $NODE_VERSIONS"
    - id: set-matrix
      run: echo "::set-output name=matrix::$NODE_VERSIONS"

  check:
    needs:
      setup
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{needs.setup.outputs.matrix}}
      - run: echo ${{fromJson(needs.setup.outputs.matrix)}}

  build:
    needs:
      setup
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.setup.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn test
      - run: printenv
